### ISSUE TITLE
ImportError: cannot import name 'ModelSchema'

### ISSUE THREAD

**Issue by pr3ssh** [Jaza/flask-restplus-patched#1]
When I try to integrate this parched package on my app, I receive

`ImportError: cannot import name 'ModelSchema'`

The import fails [here](https://github.com/Jaza/flask-restplus-patched/blob/master/flask_restplus_patched/model.py#L20). It looks like only works with [SQLAlchemy](https://github.com/marshmallow-code/flask-marshmallow/blob/386cfc4778b423869a68c7f7d1d8dfc5074e9e63/flask_marshmallow/__init__.py#L24) (I use MongoEngine).

Any ideas of how to resolve this issue? THX!

**Comment by Jaza** [comment]
Fixed in version 0.1.4 which I have just created. Hope that helps!

**Comment by pr3ssh** [comment]
Annotated to review it. THX @Jaza
